sudo: required
dist: trusty
language: python
addons:
  postgresql: 9.5
  apt:
    packages:
      - build-essential
      - git
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
      - python-pip
      - python-virtualenv
      - python-dev
      - libffi-dev
      - libssl-dev
      - postgresql-server-dev-all
      - libcurl4-openssl-dev

python:
  - '2.7'

services:
  - postgresql

before_install:
  - export DEBIAN_FRONTEND=noninteractive;
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log;
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.5-postgis-2.2
  - export WHOAHQA_COUNTRY_SETTING=whoahqa.constants.brazil_characteristics

before_script:
  - psql -U postgres -c "CREATE USER whoahqa WITH PASSWORD 'whoahqa'"
  - psql -U postgres -c "CREATE DATABASE whoahqa_test OWNER whoahqa"

script:
  - python setup.py test
