"""created OnaUser model

Revision ID: 13458cc4ea0
Revises: 14d90f7d97c5
Create Date: 2014-02-17 21:37:21.892807

"""

# revision identifiers, used by Alembic.
revision = '13458cc4ea0'
down_revision = '14d90f7d97c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ona_users',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ona_users')
    ### end Alembic commands ###
