"""initial

Revision ID: 14d90f7d97c5
Revises: None
Create Date: 2014-02-09 01:11:04.276186

"""

# revision identifiers, used by Alembic.
revision = '14d90f7d97c5'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('raw_data', postgresql.JSON(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinics',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(length=100), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
    )
    clinics_table = table('clinics',
                          sa.Column('id', sa.Integer),
                          sa.Column('code', sa.String),
                          sa.Column('name', sa.String),
    )
    op.bulk_insert(clinics_table,
                   [
                       {'code': '1A2B', 'name': 'Clinic A'},
                       {'code': '3E4G', 'name': 'Clinic B'}
                   ]
    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    users_table = table('users',
                        sa.Column('id', sa.Integer),
    )
    op.bulk_insert(users_table,
                   [
                       {},
                   ]
    )
    op.create_table('user_clinics',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('clinic_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    user_clinics_table = table('user_clinics',
                               sa.Column('user_id', sa.Integer),
                               sa.Column('clinic_id', sa.Integer),
    )
    op.bulk_insert(user_clinics_table,
                   [
                       {'user_id': 1, 'clinic_id': 1},
                   ]
    )
    op.create_table('clinic_submissions',
                    sa.Column('clinic_id', sa.Integer(), nullable=True),
                    sa.Column('submission_id', sa.Integer(), nullable=False),
                    sa.Column('characteristic', sa.String(), nullable=False),
                    sa.Column('xform_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
                    sa.ForeignKeyConstraint(['submission_id'],
                                            ['submissions.id'], ),
                    sa.PrimaryKeyConstraint('submission_id', 'characteristic',
                                            'xform_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinic_submissions')
    op.drop_table('user_clinics')
    op.drop_table('users')
    op.drop_table('clinics')
    op.drop_table('submissions')
    ### end Alembic commands ###
