"""Add User Location Table

Revision ID: 1720bf033c80
Revises: 4f530673b6de
Create Date: 2015-03-23 17:11:31.115573

"""

# revision identifiers, used by Alembic.
revision = '1720bf033c80'
down_revision = '4f530673b6de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_locations',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('location_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['location_id'], ['locations.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'location_id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_locations')
    ### end Alembic commands ###
