"""Add Locations Model

Revision ID: 193bc40f1fae
Revises: 26bb09b79c45
Create Date: 2015-01-08 11:55:03.293461

"""

# revision identifiers, used by Alembic.
revision = '193bc40f1fae'
down_revision = '26bb09b79c45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.Column('location_type',
                              sa.Enum('municipality',
                                      'state',
                                      name='LOCATION_TYPES'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_locations_location_type'),
                    'locations', ['location_type'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_location_type'), table_name='locations')
    op.drop_table('locations')
    ### end Alembic commands ###
