"""create clinic_characteristics table

Revision ID: 194054c1edb7
Revises: 2a08e5300f9
Create Date: 2014-03-11 14:42:01.336110

"""

# revision identifiers, used by Alembic.
revision = '194054c1edb7'
down_revision = '2a08e5300f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
