"""Add user settings

Revision ID: 26bb09b79c45
Revises: 3b90240bc554
Create Date: 2014-11-06 14:00:39.237299

"""

# revision identifiers, used by Alembic.
revision = '26bb09b79c45'
down_revision = '3b90240bc554'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_settings',
        sa.Column(
            'user_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('language', sa.String(length=2), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    ### end Alembic commands ###
