"""reproting period id fk in clinic characteristics

Revision ID: 3b90240bc554
Revises: c8427801156
Create Date: 2014-03-12 16:21:25.996728

"""

# revision identifiers, used by Alembic.
revision = '3b90240bc554'
down_revision = 'c8427801156'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinic_characteristics')
    op.create_table('clinic_characteristics',
        sa.Column('clinic_id', sa.Integer(), nullable=False),
        sa.Column('characteristic_id', sa.String(length=100), nullable=False),
        sa.Column('period_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
        sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], ),
        sa.PrimaryKeyConstraint('clinic_id', 'characteristic_id', 'period_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinic_characteristics')
    op.create_table('clinic_characteristics',
        sa.Column('clinic_id', sa.Integer(), nullable=False),
        sa.Column('characteristic_id', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
        sa.PrimaryKeyConstraint('clinic_id', 'characteristic_id')
    )
    ### end Alembic commands ###
