"""Add period column to Clinic Submission

Revision ID: 3fd8f83ff705
Revises: 4823423b12c7
Create Date: 2015-03-13 12:24:09.443236

"""

# revision identifiers, used by Alembic.
revision = '3fd8f83ff705'
down_revision = '4823423b12c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic_submissions', sa.Column(
        'period', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic_submissions', 'period')
    ### end Alembic commands ###
