"""Added email column to user_profile table

Revision ID: 427cac74ce9b
Revises: 1963d6d14bfd
Create Date: 2017-06-08 10:49:36.563656

"""

# revision identifiers, used by Alembic.
revision = '427cac74ce9b'
down_revision = '1963d6d14bfd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('email', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user_profiles', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles')
    op.drop_column('user_profiles', 'email')
    ### end Alembic commands ###
