"""user_clinics and user_groups PKs

Revision ID: 4b7b8ed19a69
Revises: a66701718ff
Create Date: 2014-03-04 14:07:57.372338

"""

# revision identifiers, used by Alembic.
revision = '4b7b8ed19a69'
down_revision = 'a66701718ff'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key("pk_user_clinics", "user_clinics",
                          ["user_id", "clinic_id"])
    op.create_primary_key("pk_user_groups", "user_groups",
                          ["user_id", "group_id"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pk_user_groups', 'user_groups', 'primary')
    op.drop_constraint('pk_user_clinics', 'user_clinics', 'primary')
    ### end Alembic commands ###
