"""Add valid flag to clinic submissions

Revision ID: 4f530673b6de
Revises: 3fd8f83ff705
Create Date: 2015-03-16 12:01:53.365006

"""

# revision identifiers, used by Alembic.
revision = '4f530673b6de'
down_revision = '3fd8f83ff705'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic_submissions', sa.Column(
        'valid', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic_submissions', 'valid')
    ### end Alembic commands ###
