"""Add Clinic.date_created column

Revision ID: a66701718ff
Revises: 4a6f22c2db3c
Create Date: 2014-02-26 10:55:05.196885

"""

# revision identifiers, used by Alembic.
revision = 'a66701718ff'
down_revision = '4a6f22c2db3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'clinics', sa.Column(
            'date_created', sa.DateTime(
                timezone=True), nullable=False, server_default=sa.func.now()))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'date_created')
    ### end Alembic commands ###
