"""create clinic_characteristics table

Revision ID: c8427801156
Revises: 240a53c8b88e
Create Date: 2014-03-12 12:34:08.089348

"""

# revision identifiers, used by Alembic.
revision = 'c8427801156'
down_revision = '240a53c8b88e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_characteristics',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('characteristic_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('clinic_id', 'characteristic_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinic_characteristics')
    ### end Alembic commands ###
